### ISSUE TITLE
TypeError: Cannot read property 'any' of undefined

### ISSUE THREAD

**Issue by rafarosa92** [Vizir/react-native-simple-login#5]
TypeError: Cannot read property 'any' of undefined

      at Object.<anonymous> (node_modules/react-native-simple-login/Login/Structure/Logo/Logo.js:15:33)
      at Object.<anonymous> (node_modules/react-native-simple-login/Login/Structure/index.js:1:209)
      at Object.<anonymous> (node_modules/react-native-simple-login/Login/Forms/BaseForm/BaseForm.js:3:16)

**Comment by samuel-fringeli** [comment]
got the same error

**Comment by Neutronas** [comment]
I am getting the same as well.

**Comment by nullcen** [comment]
got the same error. Does anyone solve it?

**Comment by Git4Manohar** [comment]
Did this error solve?
